services:
  postgres:
    image: postgres:18.1
    environment:
    - POSTGRES_DB=hr-autoritativa
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P4ssword!
    ports:
    - 5433:5432

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin-rh
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin123
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - postgres


#version: '3.8'
#
#services:
#  db:
#    image: postgres
#    container_name: postgres-rh
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: library
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin-rh
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - db
#
#volumes:
#  pgdata: